name: Sync to Hugging Face Spaces

on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hub
        # Replace HF_TOKEN_HERE with your actual hf_... token string
        run: git push --force https://Vedant1405:HF_TOKEN_HERE@huggingface.co/spaces/Vedant1405/GreenGrowth main:main
